<?php

namespace Database\Seeders;

use App\Models\Festival;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FestivalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $festivals = [
            [
                'name' => 'Lowlands',
                'description' => 'Groot meerdaags muziekfestival in Nederland.',
                'start_date' => '2025-08-15',
                'end_date' => '2025-08-17',
                'location_adress' => 'Spijkweg 30',
                'postal_code' => '8256 RJ',
                'city' => 'Biddinghuizen',
                'country' => 'Nederland',
                'line_up' => 'Dua Lipa, Arctic Monkeys, Bicep',
                'music_genre' => 'Pop, Indie',
                'image' => 'festivals/lowlands.jpg',
                'ticket_price' => 230.00,
                'status' => 'published',
            ],
            [
                'name' => 'Tomorrowland',
                'description' => 'Wereldberoemd dancefestival in België.',
                'start_date' => '2025-07-20',
                'end_date' => '2025-07-22',
                'location_adress' => 'De Schorre',
                'postal_code' => '2850',
                'city' => 'Boom',
                'country' => 'België',
                'line_up' => 'Martin Garrix, David Guetta, Tiësto',
                'music_genre' => 'EDM',
                'image' => 'festivals/tomorrowland.jpg',
                'ticket_price' => 310.00,
                'status' => 'published',
            ],
            [
                'name' => 'Rock Werchter',
                'description' => 'Populair rockfestival in België.',
                'start_date' => '2025-07-10',
                'end_date' => '2025-07-13',
                'location_adress' => 'Haachtsesteenweg',
                'postal_code' => '3118',
                'city' => 'Werchter',
                'country' => 'België',
                'line_up' => 'Foo Fighters, Red Hot Chili Peppers',
                'music_genre' => 'Rock',
                'image' => 'festivals/rockwerchter.jpg',
                'ticket_price' => 280.00,
                'status' => 'published',
            ],
            [
                'name' => 'Pinkpop',
                'description' => 'Een van de oudste festivals in Nederland.',
                'start_date' => '2025-06-20',
                'end_date' => '2025-06-22',
                'location_adress' => 'Megaland',
                'postal_code' => '6372 XC',
                'city' => 'Landgraaf',
                'country' => 'Nederland',
                'line_up' => 'Imagine Dragons, The Script, P!NK',
                'music_genre' => 'Pop, Rock',
                'image' => 'festivals/pinkpop.jpg',
                'ticket_price' => 195.00,
                'status' => 'published',
            ],
            [
                'name' => 'Melt Festival',
                'description' => 'Alternatief elektronisch festival in Duitsland.',
                'start_date' => '2025-07-11',
                'end_date' => '2025-07-13',
                'location_adress' => 'Ferropolis',
                'postal_code' => '06773',
                'city' => 'Gräfenhainichen',
                'country' => 'Duitsland',
                'line_up' => 'Röyksopp, Bonobo, The xx',
                'music_genre' => 'Electronic',
                'image' => 'festivals/melt.jpg',
                'ticket_price' => 215.00,
                'status' => 'published',
            ],
            [
                'name' => 'Primavera Sound',
                'description' => 'Eclectisch stadsfestival in Spanje.',
                'start_date' => '2025-06-05',
                'end_date' => '2025-06-07',
                'location_adress' => 'Parc del Fòrum',
                'postal_code' => '08019',
                'city' => 'Barcelona',
                'country' => 'Spanje',
                'line_up' => 'Tame Impala, Beck, Lorde',
                'music_genre' => 'Indie',
                'image' => 'festivals/primavera.jpg',
                'ticket_price' => 260.00,
                'status' => 'published',
            ],
            [
                'name' => 'Awakenings',
                'description' => 'Hard techno en house festival in Nederland.',
                'start_date' => '2025-07-06',
                'end_date' => '2025-07-07',
                'location_adress' => 'Spaarnwoude',
                'postal_code' => '1164',
                'city' => 'Velsen-Zuid',
                'country' => 'Nederland',
                'line_up' => 'Amelie Lens, Charlotte de Witte, Adam Beyer',
                'music_genre' => 'Techno',
                'image' => 'festivals/awakenings.jpg',
                'ticket_price' => 180.00,
                'status' => 'published',
            ],
            [
                'name' => 'Lollapalooza Berlin',
                'description' => 'Internationaal festival met pop en alternative.',
                'start_date' => '2025-09-07',
                'end_date' => '2025-09-08',
                'location_adress' => 'Olympiastadion',
                'postal_code' => '14053',
                'city' => 'Berlijn',
                'country' => 'Duitsland',
                'line_up' => 'Billie Eilish, The Killers, Kings of Leon',
                'music_genre' => 'Pop, Indie',
                'image' => 'festivals/lollapalooza.jpg',
                'ticket_price' => 240.00,
                'status' => 'published',
            ],
            // -- Nieuwe festivals hieronder --
            [
                'name' => 'Sziget Festival',
                'description' => 'Een van Europa\'s grootste culturele en muziekevenementen op een eiland in de Donau.',
                'start_date' => '2025-08-07',
                'end_date' => '2025-08-13',
                'location_adress' => 'Óbudai-sziget',
                'postal_code' => '1033',
                'city' => 'Boedapest',
                'country' => 'Hongarije',
                'line_up' => 'Ed Sheeran, Florence + The Machine, Foo Fighters',
                'music_genre' => 'Various',
                'image' => 'festivals/sziget.jpg',
                'ticket_price' => 325.00,
                'status' => 'published',
            ],
            [
                'name' => 'Creamfields',
                'description' => 'Toonaangevend dance muziekfestival in het Verenigd Koninkrijk.',
                'start_date' => '2025-08-22',
                'end_date' => '2025-08-25',
                'location_adress' => 'Daresbury Estate',
                'postal_code' => 'WA4 4AG',
                'city' => 'Halton',
                'country' => 'Verenigd Koninkrijk',
                'line_up' => 'Calvin Harris, Swedish House Mafia, Tiesto',
                'music_genre' => 'EDM',
                'image' => 'festivals/creamfields.jpg',
                'ticket_price' => 290.00,
                'status' => 'published',
            ],
            [
                'name' => 'Wacken Open Air',
                'description' => 'Het mekka voor fans van heavy metal en hardrock.',
                'start_date' => '2025-07-31',
                'end_date' => '2025-08-03',
                'location_adress' => 'Hauptstraße 47',
                'postal_code' => '25596',
                'city' => 'Wacken',
                'country' => 'Duitsland',
                'line_up' => 'Iron Maiden, Judas Priest, Slipknot',
                'music_genre' => 'Metal',
                'image' => 'festivals/wacken.jpg',
                'ticket_price' => 250.00,
                'status' => 'published',
            ],
            [
                'name' => 'Defqon.1',
                'description' => 'Het ultieme festival voor de hardere stijlen in de dancemuziek.',
                'start_date' => '2025-06-27',
                'end_date' => '2025-06-30',
                'location_adress' => 'Spijkweg 30',
                'postal_code' => '8256 RJ',
                'city' => 'Biddinghuizen',
                'country' => 'Nederland',
                'line_up' => 'Headhunterz, Angerfist, D-Block & S-te-Fan',
                'music_genre' => 'Hardstyle, Hardcore',
                'image' => 'festivals/defqon1.jpg',
                'ticket_price' => 210.00,
                'status' => 'published',
            ],
            [
                'name' => 'Glastonbury',
                'description' => 'Iconisch festival met een mix van muziek, kunst en cultuur.',
                'start_date' => '2025-06-25',
                'end_date' => '2025-06-29',
                'location_adress' => 'Worthy Farm',
                'postal_code' => 'BA4 4BY',
                'city' => 'Pilton, Somerset',
                'country' => 'Verenigd Koninkrijk',
                'line_up' => 'Paul McCartney, Taylor Swift, Kendrick Lamar',
                'music_genre' => 'Various',
                'image' => 'festivals/glastonbury.jpg',
                'ticket_price' => 340.00,
                'status' => 'sold_out',
            ],
        ];

        foreach ($festivals as $festival) {
            Festival::create($festival);
        }

    }
}
